server:
  port: 8101
spring:
  profiles:
    active: dev
  config:
    import:
      - classpath:/datasource.yml
      - classpath:/rpc.yml
      - classpath:/config.yml
      - classpath:/cache.yml
      - classpath:/base.yml
  application:
    name: business-pay

nexo:
  iap:
    apple:
      bundle-id: com.shijieyan.nexo
      issuer-id: bbe9f5f0-f5c8-4702-82f4-8a7d4ce78804
      key-id: UTQ69QMHY6
      private-key-location: classpath:AuthKey_UTQ69QMHY6.p8
      environment: Sandbox
