-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgk8aaDIjqCFFNcgZA
RhGs2A0PS9PR9QoCZWOfXvT6fZugCgYIKoZIzj0DAQehRANCAAR5VypXQIX393ID
WOvStqs/sTs/OO6w9yVCNOF+s19FOHzkdZDJxi1p2IkNuacmRd/EOFLG0gIKb52d
CROxvlsW
-----END PRIVATE KEY-----