spring:
  xxl:
    job:
      enabled: true
      adminAddresses: http://127.0.0.1:8088/xxl-job-admin
      appName: nexo-job-executor
      accessToken:
      ip: 172.20.10.2
      port: 9999
      logPath: C:\Users\user\logs\xxl-job
      logRetentionDays: 30