spring:
  elasticsearch:
    enable: false # 默认关闭
    uris: http://192.168.147.100:9200
    username: yanshijie
    password: ysj245913@.
easy-es:
  enable: true
  address: 192.168.147.100:9200
  username: yanshijie
  password: Ysj245913@.