server:
  port: 8095
spring:
  cloud:
    cloud:
      function:
        definition: buy;orderClose # 框架会自动在代码中寻找以 buy / orderClose 为名字的通道映射关系，配合后面的 out-0 或 in-0 来区分是发消息还是收消息。
    stream:
      rocketmq:
        bindings:
          orderClose-out-0:
            producer:
              producerType: Trans
              transactionListener: orderCloseTransactionListener
      bindings:
        buy-in-0:
          content-type: application/json
          destination: buy-topic
          group: trade-group
          binder: rocketmq
        orderClose-out-0:
          content-type: application/json
          destination: order-close-topic
          group: order-group
          binder: rocketmq
  config:
    import:
      - classpath:/datasource.yml
      - classpath:/rpc.yml
      - classpath:/config.yml
      - classpath:/cache.yml
      - classpath:/base.yml
      - classpath:/job.yml
      - classpath:/stream.yml
  application:
    name: business-order
